DROP DATABASE IF EXISTS BOC_AUTHENTICATED_MARKETING;
CREATE DATABASE BOC_AUTHENTICATED_MARKETING;
USE BOC_AUTHENTICATED_MARKETING;

DROP TABLE IF EXISTS BOC_CU_INFO;
CREATE TABLE BOC_CU_INFO (CU_ID VARCHAR(50) NOT NULL, SOURCE VARCHAR(20) NOT NULL, CREATE_DATE DATETIME NOT NULL, MODIFY_DATE DATETIME NOT NULL, PRIMARY KEY (CU_ID));

DROP TABLE IF EXISTS BOC_CU_API_INFO;
CREATE TABLE IF NOT EXISTS BOC_CU_API_INFO (API_ID INT NOT NULL AUTO_INCREMENT, CU_ID VARCHAR(25) NOT NULL, BASE_URL VARCHAR(300) NOT NULL, OPERATION VARCHAR(20) NOT NULL, CREATE_DATE DATETIME NOT NULL, MODIFY_DATE DATETIME NOT NULL, PRIMARY KEY (API_ID), FOREIGN KEY (CU_ID) REFERENCES BOC_CU_INFO(CU_ID));

DROP TABLE IF EXISTS BOC_CU_APP_AUTH;
CREATE TABLE BOC_CU_APP_AUTH (AUTH_ID INT NOT NULL AUTO_INCREMENT, CU_ID VARCHAR(25) NOT NULL, HEADER VARCHAR(50), KEY_STORE_PASS VARCHAR(50), KEY_ALIAS VARCHAR(50), KEY_PASS VARCHAR(50), CLIENT_ID VARCHAR(200), EMAIL VARCHAR(50), DOMAIN VARCHAR(100), ACCESS_TOKEN VARCHAR(300), TOKEN_EXPIRY_ON DATETIME, URL VARCHAR(250), USER_NAME VARCHAR(50), PASSWORD VARCHAR(50), DATABASE_TYPE VARCHAR(100), CREATE_DATE DATETIME NOT NULL, MODIFY_DATE DATETIME NOT NULL, PRIMARY KEY (AUTH_ID), FOREIGN KEY (CU_ID) REFERENCES BOC_CU_INFO(CU_ID));

DROP TABLE IF EXISTS BOC_CU_LEADS_OPPORTUNITIES;
CREATE TABLE BOC_CU_LEADS_OPPORTUNITIES (LEADS_OPPORTUNITIES_ID VARCHAR(20) NOT NULL, CU_ID VARCHAR(25) NOT NULL, NAME VARCHAR(100), DESCRIPTION VARCHAR(100), TYPE VARCHAR(100), BOCFORGE_MEMBER_NO VARCHAR(100) NOT NULL, BOCFORGE_FINANCIAL_ACCOUNT_TYPE VARCHAR(75) NOT NULL, BOCFORGE_LO_HEADER_TEXT VARCHAR(250) NOT NULL, BOCFORGE_MEMBER_RESPONSE VARCHAR(75), BOCFORGE_MEMBER_CHOICE_TEXT VARCHAR(300), BOCFORGE_MEMBER_RESPONSE_DATE DATE, BOCFORGE_MEMBER_RESPONSE_TIME DATETIME, BOCFORGE_PROMOTION_DESCRIPTION1 VARCHAR(500), BOCFORGE_PROMOTION_DESCRIPTION2 VARCHAR(500), BOCFORGE_PROMOTION_DESCRIPTION3 VARCHAR(500), BOCFORGE_PROMOTION_DESCRIPTION4 VARCHAR(500), BOCFORGE_PROMOTION_DESCRIPTION5 VARCHAR(500), BOCFORGE_PROMOTION_DESCRIPTION6 VARCHAR(500), BOCFORGE_BUTTON_CODE INT, BOCFORGE_CHOICE_CODE INT, BOCFORGE_CRM_PRIORITY INT, BOCFORGE_PROMOTION1_START_DATE DATETIME, BOCFORGE_PROMOTION2_START_DATE DATETIME, BOCFORGE_PROMOTION3_START_DATE DATETIME, BOCFORGE_PROMOTION4_START_DATE DATETIME, BOCFORGE_PROMOTION5_START_DATE DATETIME, BOCFORGE_PROMOTION6_START_DATE DATETIME, BOCFORGE_PROMOTION1_END_DATE DATETIME, BOCFORGE_PROMOTION2_END_DATE DATETIME, BOCFORGE_PROMOTION3_END_DATE DATETIME,BOCFORGE_PROMOTION4_END_DATE DATETIME,BOCFORGE_PROMOTION5_END_DATE DATETIME, BOCFORGE_PROMOTION6_END_DATE DATETIME, CREATE_DATE DATETIME NOT NULL, MODIFY_DATE DATETIME NOT NULL, PRIMARY KEY (LEADS_OPPORTUNITIES_ID), FOREIGN KEY (CU_ID) REFERENCES BOC_CU_INFO(CU_ID));

DROP TABLE IF EXISTS BOC_CU_AUDIT_INFO;
CREATE TABLE BOC_CU_AUDIT_INFO(ID INT NOT NULL AUTO_INCREMENT, TXN_ID VARCHAR(100) NOT NULL, CU_ID VARCHAR(25) NOT NULL, MEMBER_ID VARCHAR(100) NOT NULL, NOTIFICATION_ID VARCHAR(30), CHANNEL VARCHAR(10), OPERATION VARCHAR(50), OPERATION_RESULT VARCHAR(250), CREATE_DATE DATETIME NOT NULL, REQUEST JSON, PRIMARY KEY (ID), BUTTON_CODE INT, BUTTON_TEXT VARCHAR(50), CHOICE_CODE INT, CHOICE_TEXT VARCHAR(200), RESPONSE_DATE VARCHAR(20), RESPONSE_TIME VARCHAR(30), FOREIGN KEY (CU_ID) REFERENCES BOC_CU_INFO(CU_ID));


INSERT INTO BOC_CU_INFO (CU_ID, SOURCE, CREATE_DATE, MODIFY_DATE)
VALUES ('1', "SALESFORCE", NOW(), NOW());

INSERT INTO BOC_CU_INFO (CU_ID, SOURCE, CREATE_DATE, MODIFY_DATE)
VALUES ('2', "SALESFORCE", NOW(), NOW());

INSERT INTO BOC_CU_INFO (CU_ID, SOURCE, CREATE_DATE, MODIFY_DATE)
VALUES ('3', "CSV", NOW(), NOW());

INSERT INTO BOC_CU_INFO (CU_ID, SOURCE, CREATE_DATE, MODIFY_DATE)
VALUES ('4', "DB", NOW(), NOW());

INSERT INTO BOC_CU_API_INFO (API_ID, CU_ID, BASE_URL, OPERATION, CREATE_DATE, MODIFY_DATE)
VALUES (1, '1', 'https://sunshinecoast--central1.my.salesforce.com/services/data/v40.0', 'FETCH', NOW(), NOW());

INSERT INTO BOC_CU_API_INFO (API_ID, CU_ID, BASE_URL, OPERATION, CREATE_DATE, MODIFY_DATE)
VALUES (2, '2', 'https://gffinancial--fcuro.my.salesforce.com/services/data/v40.0', 'FETCH', NOW(), NOW());

INSERT INTO BOC_CU_API_INFO (API_ID, CU_ID, BASE_URL, OPERATION, CREATE_DATE, MODIFY_DATE)
VALUES (3, '2', 'https://gffinancial--fcuro.my.salesforce.com/services/data/v36.0/', 'UPDATE', NOW(), NOW());

INSERT INTO BOC_CU_API_INFO (API_ID, CU_ID, BASE_URL, OPERATION, CREATE_DATE, MODIFY_DATE)
VALUES (4, '1', 'https://sunshinecoast--central1.my.salesforce.com/services/data/v36.0/', 'UPDATE', NOW(), NOW());

INSERT INTO BOC_CU_APP_AUTH (AUTH_ID, CU_ID, HEADER, KEY_STORE_PASS, KEY_ALIAS, KEY_PASS, CLIENT_ID, EMAIL, DOMAIN, ACCESS_TOKEN, TOKEN_EXPIRY_ON, URL, USER_NAME, PASSWORD, DATABASE_TYPE, CREATE_DATE, MODIFY_DATE)
VALUES (1, '1', '{"alg":"RS256"}', 'mypass', 'auth_ss', 'mypass','3MVG9BM7anZT_gV5bYgFLN2NoGEsz9UG7Fq6IhV9JXRcgc0ntIa1EZJxqQRzZr2lfZfP3eTSFEe_kA6SEcm2t', 'sfsandboxaccess@fincuro.in', 'https://test.salesforce.com', 'some token', NOW(), '', '', '', '', NOW(), NOW());

INSERT INTO BOC_CU_APP_AUTH (AUTH_ID, CU_ID, HEADER, KEY_STORE_PASS, KEY_ALIAS, KEY_PASS, CLIENT_ID, EMAIL, DOMAIN, ACCESS_TOKEN, TOKEN_EXPIRY_ON, URL, USER_NAME, PASSWORD, DATABASE_TYPE, CREATE_DATE, MODIFY_DATE)
VALUES (2, '2', '{"alg":"RS256"}', 'mypass', 'auth_ss', 'mypass','3MVG9fK6oPRmTwx1WOngrjsji8lZ4K76w6yW1bZ7HUcSJZWe72nWwMvl7jRzVhhj5NLUautbqMiHSwJhz1OhM', 'sfsandboxaccess@fincuro.in.gf', 'https://test.salesforce.com', 'some token', NOW(), '', '', '', '', NOW(), NOW());

INSERT INTO BOC_CU_APP_AUTH (AUTH_ID, CU_ID, HEADER, KEY_STORE_PASS, KEY_ALIAS, KEY_PASS, CLIENT_ID, EMAIL, DOMAIN, ACCESS_TOKEN, TOKEN_EXPIRY_ON, URL, USER_NAME, PASSWORD, DATABASE_TYPE, CREATE_DATE, MODIFY_DATE)
VALUES (3, '4', '', '', '', '','', '', '', '', NULL, 'jdbc:mysql://52.20.219.22:3306/BOC_AUTHENTICATED_MARKETING', 'root', 'root', 'MYSQL', NOW(), NOW());