#%RAML 1.0
---
title: Deposits
version: v1
baseUri: "{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
# API resource definitions
#===============================================================
/deposits:
  displayName: deposits

  get:
    responses:
      200:
        body:
          application/json:
            type: !include schemas/deposits-response.json