#%RAML 1.0
---
title: Personal Documents
version: v1
baseUri: "document-direct-integration-service/v1"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
# API resource definitions
#===============================================================
/personaldocument:
	/personaldocumentlist:
		get:
			displayName: Document List for personal document
			queryParameters:
				cif:
					required: true
					type: string
					example: "123456"
				bu:
					required: true
					type: string
					example: "LTD"
				sortBy:
					required: true
					type: string
					example: "createDate"
				sortType:
					required: true
					type: string
					example: "desc"
				pageSize:
					required: true
					type: integer
					example: 25
				pageNumber:
					required: true
					type: integer
					example: 1
				rmPid:
					required: true
					type: string
					example: "G274125"
				documentCategories:
					required: false
					type: array
					items:
						type: string
				fromDAte:
					required: false
					type: string
					example: "2020-08-05"
				toDAte:
					required: false
					type: string
					example: "2020-08-11"
				documentStatus:
					required: false
					type: string
					example: "read"
			responses:
				200:
					body:
						application/json:
							type: !include schemas/personal-document-list.json
	/categories:
	  displayName: catagories
	  get:
		responses:
			200:
			  body:
				application/json:
				 type: !include schemas/categories.json
/documentlibrary:
  /documentlibrarycount
	get:
		responses:
		200:
			body:
			application/json:
				type: !include schemas/document-response.json